#!/usr/bin/env perl
use v5.32.0;

use Mojo::File qw(curfile);
use Path::Tiny qw(path);
use FindBin;
use lib curfile->dirname->sibling('lib')->to_string;
use blib; # curfile->dirname->sibling("..");
use Mojolicious::Commands;

# Start command line interface for application
Mojolicious::Commands->start_app('SmokesMojo');
