#!/usr/bin/perl
use strict;
use Getopt::Long;
use Smokes::Tooling::ParsedToDb
  qw(parse_new_reports_to_db parse_updates_to_db reparse_ids_to_db);
use Smokes::Helpers::Dbh;

my $verbose;
my $do_update;
my $by_id;
GetOptions("v|verbose" => \$verbose,
	   "u|update" => \$do_update,
	   "i|id" => \$by_id);

++$|;

if ($do_update) {
  parse_updates_to_db($verbose);
}
elsif ($by_id) {
  reparse_ids_to_db($verbose, \@ARGV);
}
else {
  parse_new_reports_to_db($verbose);
}

